import React from "react";
import { storiesOf } from "@storybook/react";

import Button from "./Button";

storiesOf("Button", module)
	.add("Primary", () => <Button type="primary" />)
	.add("Primary Outline", () => <Button type="primary" outline />)
	.add("Primary Faded", () => <Button type="primary" faded />)
	.add("Danger", () => <Button type="danger" />)
	.add("Danger Outline", () => <Button type="danger" outline />)
	.add("Danger Faded", () => <Button type="danger" faded red />)
	.add("Success", () => <Button type="success" />)
	.add("Success Outline", () => <Button type="success" outline />)
	.add("Success Faded", () => <Button type="success" faded />)
	.add("Warning", () => <Button type="warning" />)
	.add("Warning Outline", () => <Button type="warning" outline />)
	.add("Warning Faded", () => <Button type="warning" faded />)
	.add("Default", () => <Button type="default" />)
	.add("Default Outline", () => <Button type="default" outline />)
	.add("Default Faded", () => <Button type="default" faded />)
	.add("Large Primary", () => <Button type="primary" large />)
	.add("Large Primary Outline", () => <Button type="primary" outline large />)
	.add("Large Primary Faded", () => <Button type="primary" faded large />)
	.add("Large Danger", () => <Button type="danger" large />)
	.add("Large Danger Outline", () => <Button type="danger" outline large />)
	.add("Large Danger Faded", () => <Button type="danger" faded red large />)
	.add("Large Success", () => <Button type="success" large />)
	.add("Large Success Outline", () => <Button type="success" outline large />)
	.add("Large Success Faded", () => <Button type="success" faded large />)
	.add("Large Warning", () => <Button type="warning" large />)
	.add("Large Warning Outline", () => <Button type="warning" outline large />)
	.add("Large Warning Faded", () => <Button type="warning" faded large />)
	.add("Large Default", () => <Button type="default" large />)
	.add("Large Default Outline", () => <Button type="default" outline large />)
	.add("Large Default Faded", () => <Button type="default" faded large />);
